### ISSUE TITLE
Resetting task bug

### ISSUE THREAD

**Issue by alustig3** [pyControl/code#6]
In the "Run task" tab, after uploading a task, if I then reset a task I get the following error:
```
Traceback (most recent call last):
  File "/Users/lustiga/pyControl_official/gui/run_task_tab.py", line 267, in setup_task
    self.board.setup_state_machine(task, uploaded=self.uploaded)
  File "/Users/lustiga/pyControl_official/com/pycboard.py", line 310, in setup_state_machine
    'task_hash': _djb2_file(sm_path),
UnboundLocalError: local variable 'sm_path' referenced before assignment
```

This bug was introduced in 2073dcc40b95c234845ebbd7a3f64f8ddd77a2a2

**Comment by ThomasAkam** [comment]
Fixed in commit latest commit 96472d7059d6eecf94efccc278deb128096605a6 using fix provide by @neuromantic99 .
